# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Tom Sarduy
tagline:             'Another Front-End Engineer'
description:         'Open source projects, plugins and others front-end tools. Sometimes I write too. <br> Follow me <a href="https://twitter.com/TomSarduy" target="_blank">@tomsarduy</a>.'
url:                 http://tomsarduy.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]